# Generated by Django 3.0.5 on 2020-04-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notetaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
